use_frameworks!

platform :ios, '9.0'

target 'SCAlertController_Example' do
  pod 'SCAlertController', :path => '../'

  target 'SCAlertController_Tests' do
    inherit! :search_paths

    
  end
end
